// Enums
Enum UserStatus {
  active
  inactive
}



Enum TimeEntryType {
  in
  break_start
  break_end
  out
}

Enum EngagementStatus {
  scheduled
  completed
  paid
  canceled
}

// ==========================================
// SCHEMA: CORE (Azul)
// ==========================================

Table core.persons [headercolor: #2B6CB0] {
  id uuid [primary key]
  name string [not null]
  email string [not null]
  cellphone string [not null]
}

Table core.companies [headercolor: #2B6CB0] {
  id uuid [primary key]
  name string [not null]
  cnpj string [not null]
}


Table core.users [headercolor: #2B6CB0] {
  id uuid [primary key]
  email string [not null]
  password string [not null]
  status UserStatus
}

Table core.userCompanies [headercolor: #2B6CB0] {
  id uuid [primary key]
  companyId uuid [not null]
  userId uuid [not null]
  personId uuid
  created_at datetime
  updated_at datetime
}

// ==========================================
// SCHEMA: JOB (Laranja)
// ==========================================

Enum EmploymentStatus {
  hired
  experience
  left
}

Enum EmploymentType {
  frelancer
  dayli
  temporary
  completed
}

Table job.employees [headercolor: #D69E2E] {
  id uuid [primary key]
  companyId uuid [not null]
  personId uuid [not null]
  registerNumber number [not null]
}

Table job.employment [headercolor: #D69E2E] {
  id uuid [primary key]
  workloadId uuid [not null]
  employeeId uuid [not null]
  status EmploymentStatus [not null]
  kind EmploymentType [not null]
  register_at datetime [not null]
  left_at datetime
}

Table job.workload [headercolor: #D69E2E] {
  id uuid [primary key]
  companyId uuid [not null]
  description string [not null]
  monthly_hours integer [not null]
  weekly_hours integer [not null]
  entry_time time [not null]
  left_time time [not null]
  interval_start_at time [not null]
  interval_end_at time [not null]
}


// ==========================================
// RELATIONSHIPS / REFS
// ==========================================

// Core
Ref: core.userCompanies.companyId > core.companies.id
Ref: core.userCompanies.userId > core.users.id
Ref: core.userCompanies.personId > core.persons.id

// Job
Ref: job.employees.personId > core.persons.id
Ref: job.employees.companyId > core.companies.id
Ref: job.employment.workloadId > job.workload.id
Ref: job.workload.companyId > core.companies.id
